# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'Dockerfile'
        tags: |
          $(tag)
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1 (4350fd89-62ae-4cfc-a6d3-6dd0c8dab322)'
        azureContainerRegistry: '{"loginServer":"fitappregistry.azurecr.io", "id" : "/subscriptions/4350fd89-62ae-4cfc-a6d3-6dd0c8dab322/resourceGroups/default/providers/Microsoft.ContainerRegistry/registries/fitappregistry"}'
        dockerComposeFile: '$(Build.SourcesDirectory)/fitapp/src/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up'
