# fly.toml app configuration file generated for fitedit on 2023-07-10T18:00:40-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fitedit"
primary_region = "atl"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="fitedit_data"
  destination="/data"

#[env]
#  MY_SPECIAL_ENV = "some_value"
