version: '3.5'

services:
  fitapp:
    image: 127.0.0.1:5000/fitapp
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development #Consider changing this in Production
      - ConnectionStrings__PostgresConnection=host=postgres; database=blazor_app;user id=postgres; password=aZL343Vf!RJj
      - BlazorApp__UseSqlServer=false
      - BlazorApp__UsePostgresServer=true
      - AWS_ACCESS_KEY_ID=AKIAIXGOTDKOKLWWLZ2A
      - AWS_SECRET_ACCESS_KEY=c7ReuxGLurOZ6Em28UoN6vs3URTeg5UvJYvRFQDg
    ports:
        # Replace the values on the left by the values from launchSettings.json
      - "80:80"
      - "443:443"
    networks:
      - bb
    restart: on-failure

  postgres: 
    image: postgres
    restart: always
    volumes:
      - dbdata:/var/opt/postgres
    environment:
      - POSTGRES_PASSWORD=aZL343Vf!RJj
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blazor_app
    ports:
      - "5432:5432"
      - "5433:5433"
    networks:
      - bb

  wait_for_postgres:
    image: dadarek/wait_for_dependencies
    depends_on: 
      - postgres
    command: postgres:5432
    
volumes:
  dbdata:

networks:
  bb:
    name: bb_network
    ipam:
      driver: default
