version: '3.5'

services:
  fitapp:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Production #Consider changing this in Production
      - ConnectionStrings__PostgresConnection=host=postgres; database=blazor_app;user id=postgres; password=aZL343Vf!RJj
      - BlazorApp__UseSqlServer=false
      - BlazorApp__UsePostgresServer=true
    ports:
        # Replace the values on the left by the values from launchSettings.json
      - "80:80"
      - "443:443"
    networks:
      - bb
    restart: on-failure

  postgres: 
    image: postgres
    restart: always
    volumes:
      - dbdata:/var/opt/postgres
    environment:
      - POSTGRES_PASSWORD=aZL343Vf!RJj
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blazor_app
    ports:
      - "5433:5433"
    networks:
      - bb
      
volumes:
  dbdata:

networks:
  bb:
    name: bb_network
    ipam:
      driver: default
