name: Deploy API to Fly
on: 
  push:
    paths:
      - 'Api/**'
jobs:
  deploy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Api
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config ./scripts/fly/fitedit/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
