name: Linux
on: 
  workflow_dispatch:
  pull_request:
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review']
    paths: 
      - '**'

jobs:
  Build:
    name: Build for Linux
    runs-on: ubuntu-latest
    #runs-on: m2mini-win11
    defaults:
      run:
        # ./ is the repo root
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: pwsh ./make.ps1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          FITEDIT_RELEASES_S3_BUCKET: ${{ secrets.FITEDIT_RELEASES_S3_BUCKET }}
          FITEDIT_PLATFORM: LINUX
