name: macOS
on: 
  push:
    paths:
      - '**'
  pull_request:
jobs:
  Build:
    name: macOS Installer
      #runs-on: macos-latest
    runs-on: m2mini
    defaults:
      run:
        # ./ is the repo root
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - run: pwsh ./make.ps1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          FITEDIT_RELEASES_S3_BUCKET: ${{ secrets.FITEDIT_RELEASES_S3_BUCKET }}
          FITEDIT_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.FITEDIT_APPLE_APP_SPECIFIC_PASSWORD }}
          FITEDIT_APPLE_DEVELOPER_ID: ${{ secrets.FITEDIT_APPLE_DEVELOPER_ID }}
          FITEDIT_APPLE_TEAM_ID: ${{ secrets.FITEDIT_APPLE_TEAM_ID }}
          FITEDIT_MACOS_APP_CERT_P12_1: ${{ secrets.FITEDIT_MACOS_APP_CERT_P12_1 }}
          FITEDIT_MACOS_APP_CERT_P12_2: ${{ secrets.FITEDIT_MACOS_APP_CERT_P12_2 }}
          FITEDIT_MACOS_APP_CERT_P12_PW: ${{ secrets.FITEDIT_MACOS_APP_CERT_P12_PW }}
          FITEDIT_MACOS_INSTALL_CERT_P12_1: ${{ secrets.FITEDIT_MACOS_INSTALL_CERT_P12_1 }}
          FITEDIT_MACOS_INSTALL_CERT_P12_2: ${{ secrets.FITEDIT_MACOS_INSTALL_CERT_P12_2 }}
          FITEDIT_MACOS_INSTALL_CERT_P12_PW: ${{ secrets.FITEDIT_MACOS_INSTALL_CERT_P12_PW }}
