name: Deploy to Prod
on: 
  push:
    branches: [ main ]
    paths:
      - '**'
 
jobs:
  Deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        # ./ is the repo root
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - run: pwsh ./Go-Prod.ps1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          FITEDIT_STAGE_S3_BUCKET: ${{ secrets.FITEDIT_STAGE_S3_BUCKET }}
          FITEDIT_RELEASES_S3_BUCKET: ${{ secrets.FITEDIT_RELEASES_S3_BUCKET }}
